// spapro-react/web/src/pages/Book.vue
<template>
  <div>
    <div class="topbar">
      <div class="topbar-inner">
        <router-link class="topbar-left" to="/">
          <span class="dot"></span>
          <span>书库</span>
        </router-link>
        <div class="topbar-right">
          <span class="book-page-name">{{ title }}</span>
        </div>
      </div>
    </div>

    <div v-if="loading" class="wrap book-page">
      <div class="book-page-head">
        <div class="muted">正在加载…</div>
      </div>
    </div>

    <div v-else-if="error || !book" class="wrap book-page">
      <p class="muted">{{ error || '书不存在或加载失败' }}</p>
      <p><router-link class="link" to="/">← 返回书库</router-link></p>
    </div>

    <div v-else class="wrap book-page">
      <div class="book-page-head">
        <div class="book-page-title">{{ book.title }}</div>
        <div v-if="book.subtitle" class="book-page-sub muted">{{ book.subtitle }}</div>
        <div v-if="book.desc" class="book-page-desc muted">{{ book.desc }}</div>
        <div class="book-page-stats">
          <span>{{ (book.units || []).length }} 单元</span>
          <span class="dot">·</span>
          <span>{{ book.passageCount || 0 }} 篇文章</span>
        </div>
      </div>
      <div
        v-for="unit in (book.units || [])"
        :key="unit.id || unit.num"
        class="unit-section"
      >
        <div class="unit-head">
          <span class="unit-num">UNIT {{ unit.num }}</span>
          <span class="unit-title">{{ unit.title }}</span>
          <span class="unit-range">{{ unit.passages.length }} 篇</span>
        </div>
        <div class="passage-list">
          <router-link
            v-for="pid in unit.passages"
            :key="pid"
            class="passage-item"
            :to="`/book/${bookId}/passage/${pid}`"
          >
            <template v-if="byId[pid]">
              <div class="pi-num">PASSAGE {{ String(byId[pid].num).padStart(2, '0') }}</div>
              <div class="pi-title">{{ byId[pid].title }}</div>
              <div v-if="byId[pid].preview" class="pi-preview">{{ byId[pid].preview }}</div>
              <div class="pi-stats">词数 {{ byId[pid].wordCount || 0 }} · 核心 {{ byId[pid].coreCount || 0 }}</div>
            </template>
            <template v-else>
              <div class="pi-num">PASSAGE {{ pid.replace(/^p/, '') }}</div>
              <div class="pi-title muted">（摘要缺失）</div>
            </template>
          </router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { fetchBook } from '../api/client.js';

// 单元目录页：迁移自 app.js renderBook / renderBookContent
export default {
  name: 'Book',
  data() {
    return {
      loading: true,
      book: null,
      passages: [],
      error: null,
    };
  },
  computed: {
    bookId() {
      return this.$route.params.bookId;
    },
    title() {
      return this.loading ? '加载中…' : (this.book ? this.book.title : '');
    },
    byId() {
      const m = {};
      (this.passages || []).forEach(p => { m[p.id] = p; });
      return m;
    },
  },
  watch: {
    '$route.params.bookId'() {
      this.loadBook();
    },
  },
  created() {
    this.loadBook();
  },
  methods: {
    loadBook() {
      window.scrollTo(0, 0);
      this.loading = true;
      this.book = null;
      this.passages = [];
      this.error = null;
      fetchBook(this.bookId)
        .then(j => {
          if (!j.ok) {
            this.error = j.error || '加载失败';
          } else {
            this.book = j.book;
            this.passages = j.passages || [];
          }
          this.loading = false;
        })
        .catch(e => {
          this.error = e.message;
          this.loading = false;
        });
    },
  },
};
</script>

// spapro-react/web/src/pages/Book.jsx
import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { fetchBook } from '../api/client.js';

// 单元目录页：迁移自 app.js renderBook / renderBookContent
export default function Book() {
  const { bookId } = useParams();
  const [state, setState] = useState({ loading: true, book: null, passages: [], error: null });

  useEffect(() => {
    window.scrollTo(0, 0);
    setState({ loading: true, book: null, passages: [], error: null });
    fetchBook(bookId)
      .then(j => {
        if (!j.ok) {
          setState({ loading: false, book: null, passages: [], error: j.error || '加载失败' });
        } else {
          setState({ loading: false, book: j.book, passages: j.passages || [], error: null });
        }
      })
      .catch(e => setState({ loading: false, book: null, passages: [], error: e.message }));
  }, [bookId]);

  if (state.loading) {
    return (
      <>
        <TopBar title="加载中…" bookId={bookId} />
        <div className="wrap book-page">
          <div className="book-page-head">
            <div className="muted">正在加载…</div>
          </div>
        </div>
      </>
    );
  }
  if (state.error || !state.book) {
    return (
      <div className="wrap book-page">
        <p className="muted">{state.error || '书不存在或加载失败'}</p>
        <p><Link className="link" to="/">← 返回书库</Link></p>
      </div>
    );
  }

  const book = state.book;
  const byId = {};
  state.passages.forEach(p => { byId[p.id] = p; });

  return (
    <>
      <TopBar title={book.title} bookId={bookId} />
      <div className="wrap book-page">
        <div className="book-page-head">
          <div className="book-page-title">{book.title}</div>
          {book.subtitle ? <div className="book-page-sub muted">{book.subtitle}</div> : null}
          {book.desc ? <div className="book-page-desc muted">{book.desc}</div> : null}
          <div className="book-page-stats">
            <span>{(book.units || []).length} 单元</span>
            <span className="dot">·</span>
            <span>{book.passageCount || 0} 篇文章</span>
          </div>
        </div>
        {(book.units || []).map(unit => (
          <div className="unit-section" key={unit.id || unit.num}>
            <div className="unit-head">
              <span className="unit-num">UNIT {unit.num}</span>
              <span className="unit-title">{unit.title}</span>
              <span className="unit-range">{unit.passages.length} 篇</span>
            </div>
            <div className="passage-list">
              {unit.passages.map(pid => {
                const p = byId[pid];
                if (!p) {
                  return (
                    <Link className="passage-item" key={pid} to={`/book/${bookId}/passage/${pid}`}>
                      <div className="pi-num">PASSAGE {pid.replace(/^p/, '')}</div>
                      <div className="pi-title muted">（摘要缺失）</div>
                    </Link>
                  );
                }
                return (
                  <Link className="passage-item" key={pid} to={`/book/${bookId}/passage/${p.id}`}>
                    <div className="pi-num">PASSAGE {String(p.num).padStart(2, '0')}</div>
                    <div className="pi-title">{p.title}</div>
                    {p.preview ? <div className="pi-preview">{p.preview}</div> : null}
                    <div className="pi-stats">词数 {p.wordCount || 0} · 核心 {p.coreCount || 0}</div>
                  </Link>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </>
  );
}

function TopBar({ title, bookId }) {
  return (
    <div className="topbar">
      <div className="topbar-inner">
        <Link className="topbar-left" to="/">
          <span className="dot"></span>
          <span>书库</span>
        </Link>
        <div className="topbar-right">
          <span className="book-page-name">{title}</span>
        </div>
      </div>
    </div>
  );
}
